services:
  - type: web
    name: wa-automate
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    ports:
      - port: 8080
        protocol: http

