services:
  - type: web
    name: openwa-service
    runtime: docker
    repo: https://github.com/Kiroi663/openWA
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "8080"
    plan: starter
    disk:
      name: session-disk
      # Monte le disque Render dans /usr/src/app/sessions
      mountPath: /usr/src/app/sessions
      sizeGB: 1
